version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: wigo4it/openapi-drc:alpha
    build:
      context: ./drc
      dockerfile: Dockerfile
    hostname: drc
    restart: always
    logging: *default-logging