//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace drc.Controllers
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0))")]
    public interface IEnkelvoudiginformatieobjectController
    {
        ObservableCollection<EnkelvoudigInformatieObject> List();
    
        EnkelvoudigInformatieObject Create(EnkelvoudigInformatieObject body);
    
        /// <param name="uuid">Unieke resource identifier (UUID4)</param>
        EnkelvoudigInformatieObject Read(System.Guid uuid);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class EnkelvoudiginformatieobjectController : Controller
    {
        private IEnkelvoudiginformatieobjectController _implementation;
    
        public EnkelvoudiginformatieobjectController(IEnkelvoudiginformatieobjectController implementation)
        {
            _implementation = implementation;
        }
    
        [HttpGet, Route("enkelvoudiginformatieobjecten")]
        public ActionResult<ObservableCollection<EnkelvoudigInformatieObject>> List()
        {
            return _implementation.List();
        }
    
        [HttpPost, Route("enkelvoudiginformatieobjecten")]
        public ActionResult<EnkelvoudigInformatieObject> Create([FromBody] EnkelvoudigInformatieObject body)
        {
            return _implementation.Create(body);
        }
    
        /// <param name="uuid">Unieke resource identifier (UUID4)</param>
        [HttpGet, Route("enkelvoudiginformatieobjecten/{uuid}")]
        public ActionResult<EnkelvoudigInformatieObject> Read(System.Guid uuid)
        {
            return _implementation.Read(uuid);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0))")]
    public interface IZaakinformatieobjectController
    {
        /// <param name="zaak">URL naar de ZAAK in het ZRC.</param>
        /// <param name="informatieobject">URL to the related resource</param>
       ObservableCollection<ZaakInformatieObject> List(string zaak, string informatieobject);
    
        ZaakInformatieObject Create(ZaakInformatieObject body);
    
        /// <param name="uuid">Unieke resource identifier (UUID4)</param>
        ZaakInformatieObject Read(System.Guid uuid);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class ZaakinformatieobjectController : ControllerBase
    {
        private IZaakinformatieobjectController _implementation;
    
        public ZaakinformatieobjectController(IZaakinformatieobjectController implementation)
        {
            _implementation = implementation;
        }
    
        /// <param name="zaak">URL naar de ZAAK in het ZRC.</param>
        /// <param name="informatieobject">URL to the related resource</param>
        [HttpGet, Route("zaakinformatieobjecten")]
        public ActionResult<ObservableCollection<ZaakInformatieObject>> List(string zaak, string informatieobject)
        {
            return _implementation.List(zaak, informatieobject);
        }
    
        [HttpPost, Route("zaakinformatieobjecten")]
        public ZaakInformatieObject Create([FromBody] ZaakInformatieObject body)
        {
            return _implementation.Create(body);
        }
    
        /// <param name="uuid">Unieke resource identifier (UUID4)</param>
        [HttpGet, Route("zaakinformatieobjecten/{uuid}")]
        public ZaakInformatieObject Read(System.Guid uuid)
        {
            return _implementation.Read(uuid);
        }
    
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.70.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class EnkelvoudigInformatieObject : System.ComponentModel.INotifyPropertyChanged
    {
        private string _url;
        [Key]
        private string _identificatie;
        private string _bronorganisatie;
        private System.DateTime _creatiedatum;
        private string _titel;
        private EnkelvoudigInformatieObjectVertrouwelijkaanduiding? _vertrouwelijkaanduiding;
        private string _auteur;
        private string _formaat;
        private EnkelvoudigInformatieObjectTaal _taal;
        private string _inhoud;
        private string _link;
        private string _beschrijving;
        private string _informatieobjecttype;
    
        [Newtonsoft.Json.JsonProperty("url", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Url
        {
            get { return _url; }
            set 
            {
                if (_url != value)
                {
                    _url = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT.</summary>
        [Newtonsoft.Json.JsonProperty("identificatie", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(40, MinimumLength = 1)]
        [Key]
        public string Identificatie
        {
            get { return _identificatie; }
            set 
            {
                if (_identificatie != value)
                {
                    _identificatie = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd.</summary>
        [Newtonsoft.Json.JsonProperty("bronorganisatie", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(9)]
        public string Bronorganisatie
        {
            get { return _bronorganisatie; }
            set 
            {
                if (_bronorganisatie != value)
                {
                    _bronorganisatie = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Een datum of een gebeurtenis in de levenscyclus van het INFORMATIEOBJECT.</summary>
        [Newtonsoft.Json.JsonProperty("creatiedatum", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTime Creatiedatum
        {
            get { return _creatiedatum; }
            set 
            {
                if (_creatiedatum != value)
                {
                    _creatiedatum = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>De naam waaronder het INFORMATIEOBJECT formeel bekend is.</summary>
        [Newtonsoft.Json.JsonProperty("titel", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Titel
        {
            get { return _titel; }
            set 
            {
                if (_titel != value)
                {
                    _titel = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Aanduiding van de mate waarin het INFORMATIEOBJECT voor de openbaarheid bestemd is.</summary>
        [Newtonsoft.Json.JsonProperty("vertrouwelijkaanduiding", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public EnkelvoudigInformatieObjectVertrouwelijkaanduiding? Vertrouwelijkaanduiding
        {
            get { return _vertrouwelijkaanduiding; }
            set 
            {
                if (_vertrouwelijkaanduiding != value)
                {
                    _vertrouwelijkaanduiding = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>De persoon of organisatie die in de eerste plaats verantwoordelijk is voor het creëren van de inhoud van het INFORMATIEOBJECT.</summary>
        [Newtonsoft.Json.JsonProperty("auteur", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Auteur
        {
            get { return _auteur; }
            set 
            {
                if (_auteur != value)
                {
                    _auteur = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>De code voor de wijze waarop de inhoud van het ENKELVOUDIG INFORMATIEOBJECT is vastgelegd in een computerbestand.</summary>
        [Newtonsoft.Json.JsonProperty("formaat", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string Formaat
        {
            get { return _formaat; }
            set 
            {
                if (_formaat != value)
                {
                    _formaat = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Een taal van de intellectuele inhoud van het ENKELVOUDIG INFORMATIEOBJECT. De waardes komen uit ISO 639-2/B</summary>
        [Newtonsoft.Json.JsonProperty("taal", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public EnkelvoudigInformatieObjectTaal Taal
        {
            get { return _taal; }
            set 
            {
                if (_taal != value)
                {
                    _taal = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        [Newtonsoft.Json.JsonProperty("inhoud", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Inhoud
        {
            get { return _inhoud; }
            set 
            {
                if (_inhoud != value)
                {
                    _inhoud = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>De URL waarmee de inhoud van het INFORMATIEOBJECT op te vragen is.</summary>
        [Newtonsoft.Json.JsonProperty("link", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Link
        {
            get { return _link; }
            set 
            {
                if (_link != value)
                {
                    _link = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Een generieke beschrijving van de inhoud van het INFORMATIEOBJECT.</summary>
        [Newtonsoft.Json.JsonProperty("beschrijving", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(1000)]
        public string Beschrijving
        {
            get { return _beschrijving; }
            set 
            {
                if (_beschrijving != value)
                {
                    _beschrijving = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>URL naar de INFORMATIEOBJECTTYPE in het ZTC.</summary>
        [Newtonsoft.Json.JsonProperty("informatieobjecttype", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Informatieobjecttype
        {
            get { return _informatieobjecttype; }
            set 
            {
                if (_informatieobjecttype != value)
                {
                    _informatieobjecttype = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static EnkelvoudigInformatieObject FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<EnkelvoudigInformatieObject>(data);
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.70.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class ZaakInformatieObject : System.ComponentModel.INotifyPropertyChanged
    {
        private string _url;
        private string _zaak;
        [Key]
        private string _informatieobject;
    
        [Newtonsoft.Json.JsonProperty("url", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Url
        {
            get { return _url; }
            set 
            {
                if (_url != value)
                {
                    _url = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>URL naar de ZAAK in het ZRC.</summary>
        [Newtonsoft.Json.JsonProperty("zaak", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Zaak
        {
            get { return _zaak; }
            set 
            {
                if (_zaak != value)
                {
                    _zaak = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        [Newtonsoft.Json.JsonProperty("informatieobject", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Key]
        public string Informatieobject
        {
            get { return _informatieobject; }
            set 
            {
                if (_informatieobject != value)
                {
                    _informatieobject = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static ZaakInformatieObject FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<ZaakInformatieObject>(data);
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.70.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum EnkelvoudigInformatieObjectVertrouwelijkaanduiding
    {
        [System.Runtime.Serialization.EnumMember(Value = "openbaar")]
        Openbaar = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "beperkt openbaar")]
        Beperkt_openbaar = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "intern")]
        Intern = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "zaakvertrouwelijk")]
        Zaakvertrouwelijk = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "vertrouwelijk")]
        Vertrouwelijk = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "confidentieel")]
        Confidentieel = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "geheim")]
        Geheim = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "zeer geheim")]
        Zeer_geheim = 7,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.70.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum EnkelvoudigInformatieObjectTaal
    {
        [System.Runtime.Serialization.EnumMember(Value = "aar")]
        Aar = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "abk")]
        Abk = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "ace")]
        Ace = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "ach")]
        Ach = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "ada")]
        Ada = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "ady")]
        Ady = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "afh")]
        Afh = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "afr")]
        Afr = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = "ain")]
        Ain = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = "aka")]
        Aka = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = "akk")]
        Akk = 10,
    
        [System.Runtime.Serialization.EnumMember(Value = "ale")]
        Ale = 11,
    
        [System.Runtime.Serialization.EnumMember(Value = "alt")]
        Alt = 12,
    
        [System.Runtime.Serialization.EnumMember(Value = "amh")]
        Amh = 13,
    
        [System.Runtime.Serialization.EnumMember(Value = "ang")]
        Ang = 14,
    
        [System.Runtime.Serialization.EnumMember(Value = "anp")]
        Anp = 15,
    
        [System.Runtime.Serialization.EnumMember(Value = "ara")]
        Ara = 16,
    
        [System.Runtime.Serialization.EnumMember(Value = "arc")]
        Arc = 17,
    
        [System.Runtime.Serialization.EnumMember(Value = "arg")]
        Arg = 18,
    
        [System.Runtime.Serialization.EnumMember(Value = "arn")]
        Arn = 19,
    
        [System.Runtime.Serialization.EnumMember(Value = "arp")]
        Arp = 20,
    
        [System.Runtime.Serialization.EnumMember(Value = "arw")]
        Arw = 21,
    
        [System.Runtime.Serialization.EnumMember(Value = "asm")]
        Asm = 22,
    
        [System.Runtime.Serialization.EnumMember(Value = "ast")]
        Ast = 23,
    
        [System.Runtime.Serialization.EnumMember(Value = "ava")]
        Ava = 24,
    
        [System.Runtime.Serialization.EnumMember(Value = "ave")]
        Ave = 25,
    
        [System.Runtime.Serialization.EnumMember(Value = "awa")]
        Awa = 26,
    
        [System.Runtime.Serialization.EnumMember(Value = "aym")]
        Aym = 27,
    
        [System.Runtime.Serialization.EnumMember(Value = "aze")]
        Aze = 28,
    
        [System.Runtime.Serialization.EnumMember(Value = "bak")]
        Bak = 29,
    
        [System.Runtime.Serialization.EnumMember(Value = "bal")]
        Bal = 30,
    
        [System.Runtime.Serialization.EnumMember(Value = "bam")]
        Bam = 31,
    
        [System.Runtime.Serialization.EnumMember(Value = "ban")]
        Ban = 32,
    
        [System.Runtime.Serialization.EnumMember(Value = "bas")]
        Bas = 33,
    
        [System.Runtime.Serialization.EnumMember(Value = "bej")]
        Bej = 34,
    
        [System.Runtime.Serialization.EnumMember(Value = "bel")]
        Bel = 35,
    
        [System.Runtime.Serialization.EnumMember(Value = "bem")]
        Bem = 36,
    
        [System.Runtime.Serialization.EnumMember(Value = "ben")]
        Ben = 37,
    
        [System.Runtime.Serialization.EnumMember(Value = "bho")]
        Bho = 38,
    
        [System.Runtime.Serialization.EnumMember(Value = "bik")]
        Bik = 39,
    
        [System.Runtime.Serialization.EnumMember(Value = "bin")]
        Bin = 40,
    
        [System.Runtime.Serialization.EnumMember(Value = "bis")]
        Bis = 41,
    
        [System.Runtime.Serialization.EnumMember(Value = "bla")]
        Bla = 42,
    
        [System.Runtime.Serialization.EnumMember(Value = "tib")]
        Tib = 43,
    
        [System.Runtime.Serialization.EnumMember(Value = "bos")]
        Bos = 44,
    
        [System.Runtime.Serialization.EnumMember(Value = "bra")]
        Bra = 45,
    
        [System.Runtime.Serialization.EnumMember(Value = "bre")]
        Bre = 46,
    
        [System.Runtime.Serialization.EnumMember(Value = "bua")]
        Bua = 47,
    
        [System.Runtime.Serialization.EnumMember(Value = "bug")]
        Bug = 48,
    
        [System.Runtime.Serialization.EnumMember(Value = "bul")]
        Bul = 49,
    
        [System.Runtime.Serialization.EnumMember(Value = "byn")]
        Byn = 50,
    
        [System.Runtime.Serialization.EnumMember(Value = "cad")]
        Cad = 51,
    
        [System.Runtime.Serialization.EnumMember(Value = "car")]
        Car = 52,
    
        [System.Runtime.Serialization.EnumMember(Value = "cat")]
        Cat = 53,
    
        [System.Runtime.Serialization.EnumMember(Value = "ceb")]
        Ceb = 54,
    
        [System.Runtime.Serialization.EnumMember(Value = "cze")]
        Cze = 55,
    
        [System.Runtime.Serialization.EnumMember(Value = "cha")]
        Cha = 56,
    
        [System.Runtime.Serialization.EnumMember(Value = "chb")]
        Chb = 57,
    
        [System.Runtime.Serialization.EnumMember(Value = "che")]
        Che = 58,
    
        [System.Runtime.Serialization.EnumMember(Value = "chg")]
        Chg = 59,
    
        [System.Runtime.Serialization.EnumMember(Value = "chk")]
        Chk = 60,
    
        [System.Runtime.Serialization.EnumMember(Value = "chm")]
        Chm = 61,
    
        [System.Runtime.Serialization.EnumMember(Value = "chn")]
        Chn = 62,
    
        [System.Runtime.Serialization.EnumMember(Value = "cho")]
        Cho = 63,
    
        [System.Runtime.Serialization.EnumMember(Value = "chp")]
        Chp = 64,
    
        [System.Runtime.Serialization.EnumMember(Value = "chr")]
        Chr = 65,
    
        [System.Runtime.Serialization.EnumMember(Value = "chu")]
        Chu = 66,
    
        [System.Runtime.Serialization.EnumMember(Value = "chv")]
        Chv = 67,
    
        [System.Runtime.Serialization.EnumMember(Value = "chy")]
        Chy = 68,
    
        [System.Runtime.Serialization.EnumMember(Value = "cop")]
        Cop = 69,
    
        [System.Runtime.Serialization.EnumMember(Value = "cor")]
        Cor = 70,
    
        [System.Runtime.Serialization.EnumMember(Value = "cos")]
        Cos = 71,
    
        [System.Runtime.Serialization.EnumMember(Value = "cre")]
        Cre = 72,
    
        [System.Runtime.Serialization.EnumMember(Value = "crh")]
        Crh = 73,
    
        [System.Runtime.Serialization.EnumMember(Value = "csb")]
        Csb = 74,
    
        [System.Runtime.Serialization.EnumMember(Value = "wel")]
        Wel = 75,
    
        [System.Runtime.Serialization.EnumMember(Value = "dak")]
        Dak = 76,
    
        [System.Runtime.Serialization.EnumMember(Value = "dan")]
        Dan = 77,
    
        [System.Runtime.Serialization.EnumMember(Value = "dar")]
        Dar = 78,
    
        [System.Runtime.Serialization.EnumMember(Value = "del")]
        Del = 79,
    
        [System.Runtime.Serialization.EnumMember(Value = "den")]
        Den = 80,
    
        [System.Runtime.Serialization.EnumMember(Value = "ger")]
        Ger = 81,
    
        [System.Runtime.Serialization.EnumMember(Value = "dgr")]
        Dgr = 82,
    
        [System.Runtime.Serialization.EnumMember(Value = "din")]
        Din = 83,
    
        [System.Runtime.Serialization.EnumMember(Value = "div")]
        Div = 84,
    
        [System.Runtime.Serialization.EnumMember(Value = "doi")]
        Doi = 85,
    
        [System.Runtime.Serialization.EnumMember(Value = "dsb")]
        Dsb = 86,
    
        [System.Runtime.Serialization.EnumMember(Value = "dua")]
        Dua = 87,
    
        [System.Runtime.Serialization.EnumMember(Value = "dum")]
        Dum = 88,
    
        [System.Runtime.Serialization.EnumMember(Value = "dyu")]
        Dyu = 89,
    
        [System.Runtime.Serialization.EnumMember(Value = "dzo")]
        Dzo = 90,
    
        [System.Runtime.Serialization.EnumMember(Value = "efi")]
        Efi = 91,
    
        [System.Runtime.Serialization.EnumMember(Value = "egy")]
        Egy = 92,
    
        [System.Runtime.Serialization.EnumMember(Value = "eka")]
        Eka = 93,
    
        [System.Runtime.Serialization.EnumMember(Value = "gre")]
        Gre = 94,
    
        [System.Runtime.Serialization.EnumMember(Value = "elx")]
        Elx = 95,
    
        [System.Runtime.Serialization.EnumMember(Value = "eng")]
        Eng = 96,
    
        [System.Runtime.Serialization.EnumMember(Value = "enm")]
        Enm = 97,
    
        [System.Runtime.Serialization.EnumMember(Value = "epo")]
        Epo = 98,
    
        [System.Runtime.Serialization.EnumMember(Value = "est")]
        Est = 99,
    
        [System.Runtime.Serialization.EnumMember(Value = "baq")]
        Baq = 100,
    
        [System.Runtime.Serialization.EnumMember(Value = "ewe")]
        Ewe = 101,
    
        [System.Runtime.Serialization.EnumMember(Value = "ewo")]
        Ewo = 102,
    
        [System.Runtime.Serialization.EnumMember(Value = "fan")]
        Fan = 103,
    
        [System.Runtime.Serialization.EnumMember(Value = "fao")]
        Fao = 104,
    
        [System.Runtime.Serialization.EnumMember(Value = "per")]
        Per = 105,
    
        [System.Runtime.Serialization.EnumMember(Value = "fat")]
        Fat = 106,
    
        [System.Runtime.Serialization.EnumMember(Value = "fij")]
        Fij = 107,
    
        [System.Runtime.Serialization.EnumMember(Value = "fil")]
        Fil = 108,
    
        [System.Runtime.Serialization.EnumMember(Value = "fin")]
        Fin = 109,
    
        [System.Runtime.Serialization.EnumMember(Value = "fon")]
        Fon = 110,
    
        [System.Runtime.Serialization.EnumMember(Value = "fre")]
        Fre = 111,
    
        [System.Runtime.Serialization.EnumMember(Value = "frm")]
        Frm = 112,
    
        [System.Runtime.Serialization.EnumMember(Value = "fro")]
        Fro = 113,
    
        [System.Runtime.Serialization.EnumMember(Value = "frr")]
        Frr = 114,
    
        [System.Runtime.Serialization.EnumMember(Value = "frs")]
        Frs = 115,
    
        [System.Runtime.Serialization.EnumMember(Value = "fry")]
        Fry = 116,
    
        [System.Runtime.Serialization.EnumMember(Value = "ful")]
        Ful = 117,
    
        [System.Runtime.Serialization.EnumMember(Value = "fur")]
        Fur = 118,
    
        [System.Runtime.Serialization.EnumMember(Value = "gaa")]
        Gaa = 119,
    
        [System.Runtime.Serialization.EnumMember(Value = "gay")]
        Gay = 120,
    
        [System.Runtime.Serialization.EnumMember(Value = "gba")]
        Gba = 121,
    
        [System.Runtime.Serialization.EnumMember(Value = "gez")]
        Gez = 122,
    
        [System.Runtime.Serialization.EnumMember(Value = "gil")]
        Gil = 123,
    
        [System.Runtime.Serialization.EnumMember(Value = "gla")]
        Gla = 124,
    
        [System.Runtime.Serialization.EnumMember(Value = "gle")]
        Gle = 125,
    
        [System.Runtime.Serialization.EnumMember(Value = "glg")]
        Glg = 126,
    
        [System.Runtime.Serialization.EnumMember(Value = "glv")]
        Glv = 127,
    
        [System.Runtime.Serialization.EnumMember(Value = "gmh")]
        Gmh = 128,
    
        [System.Runtime.Serialization.EnumMember(Value = "goh")]
        Goh = 129,
    
        [System.Runtime.Serialization.EnumMember(Value = "gon")]
        Gon = 130,
    
        [System.Runtime.Serialization.EnumMember(Value = "gor")]
        Gor = 131,
    
        [System.Runtime.Serialization.EnumMember(Value = "got")]
        Got = 132,
    
        [System.Runtime.Serialization.EnumMember(Value = "grb")]
        Grb = 133,
    
        [System.Runtime.Serialization.EnumMember(Value = "grc")]
        Grc = 134,
    
        [System.Runtime.Serialization.EnumMember(Value = "grn")]
        Grn = 135,
    
        [System.Runtime.Serialization.EnumMember(Value = "gsw")]
        Gsw = 136,
    
        [System.Runtime.Serialization.EnumMember(Value = "guj")]
        Guj = 137,
    
        [System.Runtime.Serialization.EnumMember(Value = "gwi")]
        Gwi = 138,
    
        [System.Runtime.Serialization.EnumMember(Value = "hai")]
        Hai = 139,
    
        [System.Runtime.Serialization.EnumMember(Value = "hat")]
        Hat = 140,
    
        [System.Runtime.Serialization.EnumMember(Value = "hau")]
        Hau = 141,
    
        [System.Runtime.Serialization.EnumMember(Value = "haw")]
        Haw = 142,
    
        [System.Runtime.Serialization.EnumMember(Value = "heb")]
        Heb = 143,
    
        [System.Runtime.Serialization.EnumMember(Value = "her")]
        Her = 144,
    
        [System.Runtime.Serialization.EnumMember(Value = "hil")]
        Hil = 145,
    
        [System.Runtime.Serialization.EnumMember(Value = "hin")]
        Hin = 146,
    
        [System.Runtime.Serialization.EnumMember(Value = "hit")]
        Hit = 147,
    
        [System.Runtime.Serialization.EnumMember(Value = "hmn")]
        Hmn = 148,
    
        [System.Runtime.Serialization.EnumMember(Value = "hmo")]
        Hmo = 149,
    
        [System.Runtime.Serialization.EnumMember(Value = "hrv")]
        Hrv = 150,
    
        [System.Runtime.Serialization.EnumMember(Value = "hsb")]
        Hsb = 151,
    
        [System.Runtime.Serialization.EnumMember(Value = "hun")]
        Hun = 152,
    
        [System.Runtime.Serialization.EnumMember(Value = "hup")]
        Hup = 153,
    
        [System.Runtime.Serialization.EnumMember(Value = "arm")]
        Arm = 154,
    
        [System.Runtime.Serialization.EnumMember(Value = "iba")]
        Iba = 155,
    
        [System.Runtime.Serialization.EnumMember(Value = "ibo")]
        Ibo = 156,
    
        [System.Runtime.Serialization.EnumMember(Value = "ido")]
        Ido = 157,
    
        [System.Runtime.Serialization.EnumMember(Value = "iii")]
        Iii = 158,
    
        [System.Runtime.Serialization.EnumMember(Value = "iku")]
        Iku = 159,
    
        [System.Runtime.Serialization.EnumMember(Value = "ile")]
        Ile = 160,
    
        [System.Runtime.Serialization.EnumMember(Value = "ilo")]
        Ilo = 161,
    
        [System.Runtime.Serialization.EnumMember(Value = "ina")]
        Ina = 162,
    
        [System.Runtime.Serialization.EnumMember(Value = "ind")]
        Ind = 163,
    
        [System.Runtime.Serialization.EnumMember(Value = "inh")]
        Inh = 164,
    
        [System.Runtime.Serialization.EnumMember(Value = "ipk")]
        Ipk = 165,
    
        [System.Runtime.Serialization.EnumMember(Value = "ice")]
        Ice = 166,
    
        [System.Runtime.Serialization.EnumMember(Value = "ita")]
        Ita = 167,
    
        [System.Runtime.Serialization.EnumMember(Value = "jav")]
        Jav = 168,
    
        [System.Runtime.Serialization.EnumMember(Value = "jbo")]
        Jbo = 169,
    
        [System.Runtime.Serialization.EnumMember(Value = "jpn")]
        Jpn = 170,
    
        [System.Runtime.Serialization.EnumMember(Value = "jpr")]
        Jpr = 171,
    
        [System.Runtime.Serialization.EnumMember(Value = "jrb")]
        Jrb = 172,
    
        [System.Runtime.Serialization.EnumMember(Value = "kaa")]
        Kaa = 173,
    
        [System.Runtime.Serialization.EnumMember(Value = "kab")]
        Kab = 174,
    
        [System.Runtime.Serialization.EnumMember(Value = "kac")]
        Kac = 175,
    
        [System.Runtime.Serialization.EnumMember(Value = "kal")]
        Kal = 176,
    
        [System.Runtime.Serialization.EnumMember(Value = "kam")]
        Kam = 177,
    
        [System.Runtime.Serialization.EnumMember(Value = "kan")]
        Kan = 178,
    
        [System.Runtime.Serialization.EnumMember(Value = "kas")]
        Kas = 179,
    
        [System.Runtime.Serialization.EnumMember(Value = "geo")]
        Geo = 180,
    
        [System.Runtime.Serialization.EnumMember(Value = "kau")]
        Kau = 181,
    
        [System.Runtime.Serialization.EnumMember(Value = "kaw")]
        Kaw = 182,
    
        [System.Runtime.Serialization.EnumMember(Value = "kaz")]
        Kaz = 183,
    
        [System.Runtime.Serialization.EnumMember(Value = "kbd")]
        Kbd = 184,
    
        [System.Runtime.Serialization.EnumMember(Value = "kha")]
        Kha = 185,
    
        [System.Runtime.Serialization.EnumMember(Value = "khm")]
        Khm = 186,
    
        [System.Runtime.Serialization.EnumMember(Value = "kho")]
        Kho = 187,
    
        [System.Runtime.Serialization.EnumMember(Value = "kik")]
        Kik = 188,
    
        [System.Runtime.Serialization.EnumMember(Value = "kin")]
        Kin = 189,
    
        [System.Runtime.Serialization.EnumMember(Value = "kir")]
        Kir = 190,
    
        [System.Runtime.Serialization.EnumMember(Value = "kmb")]
        Kmb = 191,
    
        [System.Runtime.Serialization.EnumMember(Value = "kok")]
        Kok = 192,
    
        [System.Runtime.Serialization.EnumMember(Value = "kom")]
        Kom = 193,
    
        [System.Runtime.Serialization.EnumMember(Value = "kon")]
        Kon = 194,
    
        [System.Runtime.Serialization.EnumMember(Value = "kor")]
        Kor = 195,
    
        [System.Runtime.Serialization.EnumMember(Value = "kos")]
        Kos = 196,
    
        [System.Runtime.Serialization.EnumMember(Value = "kpe")]
        Kpe = 197,
    
        [System.Runtime.Serialization.EnumMember(Value = "krc")]
        Krc = 198,
    
        [System.Runtime.Serialization.EnumMember(Value = "krl")]
        Krl = 199,
    
        [System.Runtime.Serialization.EnumMember(Value = "kru")]
        Kru = 200,
    
        [System.Runtime.Serialization.EnumMember(Value = "kua")]
        Kua = 201,
    
        [System.Runtime.Serialization.EnumMember(Value = "kum")]
        Kum = 202,
    
        [System.Runtime.Serialization.EnumMember(Value = "kur")]
        Kur = 203,
    
        [System.Runtime.Serialization.EnumMember(Value = "kut")]
        Kut = 204,
    
        [System.Runtime.Serialization.EnumMember(Value = "lad")]
        Lad = 205,
    
        [System.Runtime.Serialization.EnumMember(Value = "lah")]
        Lah = 206,
    
        [System.Runtime.Serialization.EnumMember(Value = "lam")]
        Lam = 207,
    
        [System.Runtime.Serialization.EnumMember(Value = "lao")]
        Lao = 208,
    
        [System.Runtime.Serialization.EnumMember(Value = "lat")]
        Lat = 209,
    
        [System.Runtime.Serialization.EnumMember(Value = "lav")]
        Lav = 210,
    
        [System.Runtime.Serialization.EnumMember(Value = "lez")]
        Lez = 211,
    
        [System.Runtime.Serialization.EnumMember(Value = "lim")]
        Lim = 212,
    
        [System.Runtime.Serialization.EnumMember(Value = "lin")]
        Lin = 213,
    
        [System.Runtime.Serialization.EnumMember(Value = "lit")]
        Lit = 214,
    
        [System.Runtime.Serialization.EnumMember(Value = "lol")]
        Lol = 215,
    
        [System.Runtime.Serialization.EnumMember(Value = "loz")]
        Loz = 216,
    
        [System.Runtime.Serialization.EnumMember(Value = "ltz")]
        Ltz = 217,
    
        [System.Runtime.Serialization.EnumMember(Value = "lua")]
        Lua = 218,
    
        [System.Runtime.Serialization.EnumMember(Value = "lub")]
        Lub = 219,
    
        [System.Runtime.Serialization.EnumMember(Value = "lug")]
        Lug = 220,
    
        [System.Runtime.Serialization.EnumMember(Value = "lui")]
        Lui = 221,
    
        [System.Runtime.Serialization.EnumMember(Value = "lun")]
        Lun = 222,
    
        [System.Runtime.Serialization.EnumMember(Value = "luo")]
        Luo = 223,
    
        [System.Runtime.Serialization.EnumMember(Value = "lus")]
        Lus = 224,
    
        [System.Runtime.Serialization.EnumMember(Value = "mad")]
        Mad = 225,
    
        [System.Runtime.Serialization.EnumMember(Value = "mag")]
        Mag = 226,
    
        [System.Runtime.Serialization.EnumMember(Value = "mah")]
        Mah = 227,
    
        [System.Runtime.Serialization.EnumMember(Value = "mai")]
        Mai = 228,
    
        [System.Runtime.Serialization.EnumMember(Value = "mak")]
        Mak = 229,
    
        [System.Runtime.Serialization.EnumMember(Value = "mal")]
        Mal = 230,
    
        [System.Runtime.Serialization.EnumMember(Value = "man")]
        Man = 231,
    
        [System.Runtime.Serialization.EnumMember(Value = "mar")]
        Mar = 232,
    
        [System.Runtime.Serialization.EnumMember(Value = "mas")]
        Mas = 233,
    
        [System.Runtime.Serialization.EnumMember(Value = "mdf")]
        Mdf = 234,
    
        [System.Runtime.Serialization.EnumMember(Value = "mdr")]
        Mdr = 235,
    
        [System.Runtime.Serialization.EnumMember(Value = "men")]
        Men = 236,
    
        [System.Runtime.Serialization.EnumMember(Value = "mga")]
        Mga = 237,
    
        [System.Runtime.Serialization.EnumMember(Value = "mic")]
        Mic = 238,
    
        [System.Runtime.Serialization.EnumMember(Value = "min")]
        Min = 239,
    
        [System.Runtime.Serialization.EnumMember(Value = "mis")]
        Mis = 240,
    
        [System.Runtime.Serialization.EnumMember(Value = "mac")]
        Mac = 241,
    
        [System.Runtime.Serialization.EnumMember(Value = "mlg")]
        Mlg = 242,
    
        [System.Runtime.Serialization.EnumMember(Value = "mlt")]
        Mlt = 243,
    
        [System.Runtime.Serialization.EnumMember(Value = "mnc")]
        Mnc = 244,
    
        [System.Runtime.Serialization.EnumMember(Value = "mni")]
        Mni = 245,
    
        [System.Runtime.Serialization.EnumMember(Value = "moh")]
        Moh = 246,
    
        [System.Runtime.Serialization.EnumMember(Value = "mon")]
        Mon = 247,
    
        [System.Runtime.Serialization.EnumMember(Value = "mos")]
        Mos = 248,
    
        [System.Runtime.Serialization.EnumMember(Value = "mao")]
        Mao = 249,
    
        [System.Runtime.Serialization.EnumMember(Value = "may")]
        May = 250,
    
        [System.Runtime.Serialization.EnumMember(Value = "mul")]
        Mul = 251,
    
        [System.Runtime.Serialization.EnumMember(Value = "mus")]
        Mus = 252,
    
        [System.Runtime.Serialization.EnumMember(Value = "mwl")]
        Mwl = 253,
    
        [System.Runtime.Serialization.EnumMember(Value = "mwr")]
        Mwr = 254,
    
        [System.Runtime.Serialization.EnumMember(Value = "bur")]
        Bur = 255,
    
        [System.Runtime.Serialization.EnumMember(Value = "myv")]
        Myv = 256,
    
        [System.Runtime.Serialization.EnumMember(Value = "nap")]
        Nap = 257,
    
        [System.Runtime.Serialization.EnumMember(Value = "nau")]
        Nau = 258,
    
        [System.Runtime.Serialization.EnumMember(Value = "nav")]
        Nav = 259,
    
        [System.Runtime.Serialization.EnumMember(Value = "nbl")]
        Nbl = 260,
    
        [System.Runtime.Serialization.EnumMember(Value = "nde")]
        Nde = 261,
    
        [System.Runtime.Serialization.EnumMember(Value = "ndo")]
        Ndo = 262,
    
        [System.Runtime.Serialization.EnumMember(Value = "nds")]
        Nds = 263,
    
        [System.Runtime.Serialization.EnumMember(Value = "nep")]
        Nep = 264,
    
        [System.Runtime.Serialization.EnumMember(Value = "new")]
        New = 265,
    
        [System.Runtime.Serialization.EnumMember(Value = "nia")]
        Nia = 266,
    
        [System.Runtime.Serialization.EnumMember(Value = "niu")]
        Niu = 267,
    
        [System.Runtime.Serialization.EnumMember(Value = "dut")]
        Dut = 268,
    
        [System.Runtime.Serialization.EnumMember(Value = "nno")]
        Nno = 269,
    
        [System.Runtime.Serialization.EnumMember(Value = "nob")]
        Nob = 270,
    
        [System.Runtime.Serialization.EnumMember(Value = "nog")]
        Nog = 271,
    
        [System.Runtime.Serialization.EnumMember(Value = "non")]
        Non = 272,
    
        [System.Runtime.Serialization.EnumMember(Value = "nor")]
        Nor = 273,
    
        [System.Runtime.Serialization.EnumMember(Value = "nqo")]
        Nqo = 274,
    
        [System.Runtime.Serialization.EnumMember(Value = "nso")]
        Nso = 275,
    
        [System.Runtime.Serialization.EnumMember(Value = "nwc")]
        Nwc = 276,
    
        [System.Runtime.Serialization.EnumMember(Value = "nya")]
        Nya = 277,
    
        [System.Runtime.Serialization.EnumMember(Value = "nym")]
        Nym = 278,
    
        [System.Runtime.Serialization.EnumMember(Value = "nyn")]
        Nyn = 279,
    
        [System.Runtime.Serialization.EnumMember(Value = "nyo")]
        Nyo = 280,
    
        [System.Runtime.Serialization.EnumMember(Value = "nzi")]
        Nzi = 281,
    
        [System.Runtime.Serialization.EnumMember(Value = "oci")]
        Oci = 282,
    
        [System.Runtime.Serialization.EnumMember(Value = "oji")]
        Oji = 283,
    
        [System.Runtime.Serialization.EnumMember(Value = "ori")]
        Ori = 284,
    
        [System.Runtime.Serialization.EnumMember(Value = "orm")]
        Orm = 285,
    
        [System.Runtime.Serialization.EnumMember(Value = "osa")]
        Osa = 286,
    
        [System.Runtime.Serialization.EnumMember(Value = "oss")]
        Oss = 287,
    
        [System.Runtime.Serialization.EnumMember(Value = "ota")]
        Ota = 288,
    
        [System.Runtime.Serialization.EnumMember(Value = "pag")]
        Pag = 289,
    
        [System.Runtime.Serialization.EnumMember(Value = "pal")]
        Pal = 290,
    
        [System.Runtime.Serialization.EnumMember(Value = "pam")]
        Pam = 291,
    
        [System.Runtime.Serialization.EnumMember(Value = "pan")]
        Pan = 292,
    
        [System.Runtime.Serialization.EnumMember(Value = "pap")]
        Pap = 293,
    
        [System.Runtime.Serialization.EnumMember(Value = "pau")]
        Pau = 294,
    
        [System.Runtime.Serialization.EnumMember(Value = "peo")]
        Peo = 295,
    
        [System.Runtime.Serialization.EnumMember(Value = "phn")]
        Phn = 296,
    
        [System.Runtime.Serialization.EnumMember(Value = "pli")]
        Pli = 297,
    
        [System.Runtime.Serialization.EnumMember(Value = "pol")]
        Pol = 298,
    
        [System.Runtime.Serialization.EnumMember(Value = "pon")]
        Pon = 299,
    
        [System.Runtime.Serialization.EnumMember(Value = "por")]
        Por = 300,
    
        [System.Runtime.Serialization.EnumMember(Value = "pro")]
        Pro = 301,
    
        [System.Runtime.Serialization.EnumMember(Value = "pus")]
        Pus = 302,
    
        [System.Runtime.Serialization.EnumMember(Value = "que")]
        Que = 303,
    
        [System.Runtime.Serialization.EnumMember(Value = "raj")]
        Raj = 304,
    
        [System.Runtime.Serialization.EnumMember(Value = "rap")]
        Rap = 305,
    
        [System.Runtime.Serialization.EnumMember(Value = "rar")]
        Rar = 306,
    
        [System.Runtime.Serialization.EnumMember(Value = "roh")]
        Roh = 307,
    
        [System.Runtime.Serialization.EnumMember(Value = "rom")]
        Rom = 308,
    
        [System.Runtime.Serialization.EnumMember(Value = "rum")]
        Rum = 309,
    
        [System.Runtime.Serialization.EnumMember(Value = "run")]
        Run = 310,
    
        [System.Runtime.Serialization.EnumMember(Value = "rup")]
        Rup = 311,
    
        [System.Runtime.Serialization.EnumMember(Value = "rus")]
        Rus = 312,
    
        [System.Runtime.Serialization.EnumMember(Value = "sad")]
        Sad = 313,
    
        [System.Runtime.Serialization.EnumMember(Value = "sag")]
        Sag = 314,
    
        [System.Runtime.Serialization.EnumMember(Value = "sah")]
        Sah = 315,
    
        [System.Runtime.Serialization.EnumMember(Value = "sam")]
        Sam = 316,
    
        [System.Runtime.Serialization.EnumMember(Value = "san")]
        San = 317,
    
        [System.Runtime.Serialization.EnumMember(Value = "sas")]
        Sas = 318,
    
        [System.Runtime.Serialization.EnumMember(Value = "sat")]
        Sat = 319,
    
        [System.Runtime.Serialization.EnumMember(Value = "scn")]
        Scn = 320,
    
        [System.Runtime.Serialization.EnumMember(Value = "sco")]
        Sco = 321,
    
        [System.Runtime.Serialization.EnumMember(Value = "sel")]
        Sel = 322,
    
        [System.Runtime.Serialization.EnumMember(Value = "sga")]
        Sga = 323,
    
        [System.Runtime.Serialization.EnumMember(Value = "shn")]
        Shn = 324,
    
        [System.Runtime.Serialization.EnumMember(Value = "sid")]
        Sid = 325,
    
        [System.Runtime.Serialization.EnumMember(Value = "sin")]
        Sin = 326,
    
        [System.Runtime.Serialization.EnumMember(Value = "slo")]
        Slo = 327,
    
        [System.Runtime.Serialization.EnumMember(Value = "slv")]
        Slv = 328,
    
        [System.Runtime.Serialization.EnumMember(Value = "sma")]
        Sma = 329,
    
        [System.Runtime.Serialization.EnumMember(Value = "sme")]
        Sme = 330,
    
        [System.Runtime.Serialization.EnumMember(Value = "smj")]
        Smj = 331,
    
        [System.Runtime.Serialization.EnumMember(Value = "smn")]
        Smn = 332,
    
        [System.Runtime.Serialization.EnumMember(Value = "smo")]
        Smo = 333,
    
        [System.Runtime.Serialization.EnumMember(Value = "sms")]
        Sms = 334,
    
        [System.Runtime.Serialization.EnumMember(Value = "sna")]
        Sna = 335,
    
        [System.Runtime.Serialization.EnumMember(Value = "snd")]
        Snd = 336,
    
        [System.Runtime.Serialization.EnumMember(Value = "snk")]
        Snk = 337,
    
        [System.Runtime.Serialization.EnumMember(Value = "sog")]
        Sog = 338,
    
        [System.Runtime.Serialization.EnumMember(Value = "som")]
        Som = 339,
    
        [System.Runtime.Serialization.EnumMember(Value = "sot")]
        Sot = 340,
    
        [System.Runtime.Serialization.EnumMember(Value = "spa")]
        Spa = 341,
    
        [System.Runtime.Serialization.EnumMember(Value = "alb")]
        Alb = 342,
    
        [System.Runtime.Serialization.EnumMember(Value = "srd")]
        Srd = 343,
    
        [System.Runtime.Serialization.EnumMember(Value = "srn")]
        Srn = 344,
    
        [System.Runtime.Serialization.EnumMember(Value = "srp")]
        Srp = 345,
    
        [System.Runtime.Serialization.EnumMember(Value = "srr")]
        Srr = 346,
    
        [System.Runtime.Serialization.EnumMember(Value = "ssw")]
        Ssw = 347,
    
        [System.Runtime.Serialization.EnumMember(Value = "suk")]
        Suk = 348,
    
        [System.Runtime.Serialization.EnumMember(Value = "sun")]
        Sun = 349,
    
        [System.Runtime.Serialization.EnumMember(Value = "sus")]
        Sus = 350,
    
        [System.Runtime.Serialization.EnumMember(Value = "sux")]
        Sux = 351,
    
        [System.Runtime.Serialization.EnumMember(Value = "swa")]
        Swa = 352,
    
        [System.Runtime.Serialization.EnumMember(Value = "swe")]
        Swe = 353,
    
        [System.Runtime.Serialization.EnumMember(Value = "syc")]
        Syc = 354,
    
        [System.Runtime.Serialization.EnumMember(Value = "syr")]
        Syr = 355,
    
        [System.Runtime.Serialization.EnumMember(Value = "tah")]
        Tah = 356,
    
        [System.Runtime.Serialization.EnumMember(Value = "tam")]
        Tam = 357,
    
        [System.Runtime.Serialization.EnumMember(Value = "tat")]
        Tat = 358,
    
        [System.Runtime.Serialization.EnumMember(Value = "tel")]
        Tel = 359,
    
        [System.Runtime.Serialization.EnumMember(Value = "tem")]
        Tem = 360,
    
        [System.Runtime.Serialization.EnumMember(Value = "ter")]
        Ter = 361,
    
        [System.Runtime.Serialization.EnumMember(Value = "tet")]
        Tet = 362,
    
        [System.Runtime.Serialization.EnumMember(Value = "tgk")]
        Tgk = 363,
    
        [System.Runtime.Serialization.EnumMember(Value = "tgl")]
        Tgl = 364,
    
        [System.Runtime.Serialization.EnumMember(Value = "tha")]
        Tha = 365,
    
        [System.Runtime.Serialization.EnumMember(Value = "tig")]
        Tig = 366,
    
        [System.Runtime.Serialization.EnumMember(Value = "tir")]
        Tir = 367,
    
        [System.Runtime.Serialization.EnumMember(Value = "tiv")]
        Tiv = 368,
    
        [System.Runtime.Serialization.EnumMember(Value = "tkl")]
        Tkl = 369,
    
        [System.Runtime.Serialization.EnumMember(Value = "tlh")]
        Tlh = 370,
    
        [System.Runtime.Serialization.EnumMember(Value = "tli")]
        Tli = 371,
    
        [System.Runtime.Serialization.EnumMember(Value = "tmh")]
        Tmh = 372,
    
        [System.Runtime.Serialization.EnumMember(Value = "tog")]
        Tog = 373,
    
        [System.Runtime.Serialization.EnumMember(Value = "ton")]
        Ton = 374,
    
        [System.Runtime.Serialization.EnumMember(Value = "tpi")]
        Tpi = 375,
    
        [System.Runtime.Serialization.EnumMember(Value = "tsi")]
        Tsi = 376,
    
        [System.Runtime.Serialization.EnumMember(Value = "tsn")]
        Tsn = 377,
    
        [System.Runtime.Serialization.EnumMember(Value = "tso")]
        Tso = 378,
    
        [System.Runtime.Serialization.EnumMember(Value = "tuk")]
        Tuk = 379,
    
        [System.Runtime.Serialization.EnumMember(Value = "tum")]
        Tum = 380,
    
        [System.Runtime.Serialization.EnumMember(Value = "tur")]
        Tur = 381,
    
        [System.Runtime.Serialization.EnumMember(Value = "tvl")]
        Tvl = 382,
    
        [System.Runtime.Serialization.EnumMember(Value = "twi")]
        Twi = 383,
    
        [System.Runtime.Serialization.EnumMember(Value = "tyv")]
        Tyv = 384,
    
        [System.Runtime.Serialization.EnumMember(Value = "udm")]
        Udm = 385,
    
        [System.Runtime.Serialization.EnumMember(Value = "uga")]
        Uga = 386,
    
        [System.Runtime.Serialization.EnumMember(Value = "uig")]
        Uig = 387,
    
        [System.Runtime.Serialization.EnumMember(Value = "ukr")]
        Ukr = 388,
    
        [System.Runtime.Serialization.EnumMember(Value = "umb")]
        Umb = 389,
    
        [System.Runtime.Serialization.EnumMember(Value = "und")]
        Und = 390,
    
        [System.Runtime.Serialization.EnumMember(Value = "urd")]
        Urd = 391,
    
        [System.Runtime.Serialization.EnumMember(Value = "uzb")]
        Uzb = 392,
    
        [System.Runtime.Serialization.EnumMember(Value = "vai")]
        Vai = 393,
    
        [System.Runtime.Serialization.EnumMember(Value = "ven")]
        Ven = 394,
    
        [System.Runtime.Serialization.EnumMember(Value = "vie")]
        Vie = 395,
    
        [System.Runtime.Serialization.EnumMember(Value = "vol")]
        Vol = 396,
    
        [System.Runtime.Serialization.EnumMember(Value = "vot")]
        Vot = 397,
    
        [System.Runtime.Serialization.EnumMember(Value = "wal")]
        Wal = 398,
    
        [System.Runtime.Serialization.EnumMember(Value = "war")]
        War = 399,
    
        [System.Runtime.Serialization.EnumMember(Value = "was")]
        Was = 400,
    
        [System.Runtime.Serialization.EnumMember(Value = "wln")]
        Wln = 401,
    
        [System.Runtime.Serialization.EnumMember(Value = "wol")]
        Wol = 402,
    
        [System.Runtime.Serialization.EnumMember(Value = "xal")]
        Xal = 403,
    
        [System.Runtime.Serialization.EnumMember(Value = "xho")]
        Xho = 404,
    
        [System.Runtime.Serialization.EnumMember(Value = "yao")]
        Yao = 405,
    
        [System.Runtime.Serialization.EnumMember(Value = "yap")]
        Yap = 406,
    
        [System.Runtime.Serialization.EnumMember(Value = "yid")]
        Yid = 407,
    
        [System.Runtime.Serialization.EnumMember(Value = "yor")]
        Yor = 408,
    
        [System.Runtime.Serialization.EnumMember(Value = "zap")]
        Zap = 409,
    
        [System.Runtime.Serialization.EnumMember(Value = "zbl")]
        Zbl = 410,
    
        [System.Runtime.Serialization.EnumMember(Value = "zen")]
        Zen = 411,
    
        [System.Runtime.Serialization.EnumMember(Value = "zgh")]
        Zgh = 412,
    
        [System.Runtime.Serialization.EnumMember(Value = "zha")]
        Zha = 413,
    
        [System.Runtime.Serialization.EnumMember(Value = "chi")]
        Chi = 414,
    
        [System.Runtime.Serialization.EnumMember(Value = "zul")]
        Zul = 415,
    
        [System.Runtime.Serialization.EnumMember(Value = "zun")]
        Zun = 416,
    
        [System.Runtime.Serialization.EnumMember(Value = "zxx")]
        Zxx = 417,
    
        [System.Runtime.Serialization.EnumMember(Value = "zza")]
        Zza = 418,
    
        [System.Runtime.Serialization.EnumMember(Value = "afa")]
        Afa = 419,
    
        [System.Runtime.Serialization.EnumMember(Value = "alg")]
        Alg = 420,
    
        [System.Runtime.Serialization.EnumMember(Value = "apa")]
        Apa = 421,
    
        [System.Runtime.Serialization.EnumMember(Value = "art")]
        Art = 422,
    
        [System.Runtime.Serialization.EnumMember(Value = "ath")]
        Ath = 423,
    
        [System.Runtime.Serialization.EnumMember(Value = "aus")]
        Aus = 424,
    
        [System.Runtime.Serialization.EnumMember(Value = "bad")]
        Bad = 425,
    
        [System.Runtime.Serialization.EnumMember(Value = "bai")]
        Bai = 426,
    
        [System.Runtime.Serialization.EnumMember(Value = "bat")]
        Bat = 427,
    
        [System.Runtime.Serialization.EnumMember(Value = "ber")]
        Ber = 428,
    
        [System.Runtime.Serialization.EnumMember(Value = "bih")]
        Bih = 429,
    
        [System.Runtime.Serialization.EnumMember(Value = "bnt")]
        Bnt = 430,
    
        [System.Runtime.Serialization.EnumMember(Value = "btk")]
        Btk = 431,
    
        [System.Runtime.Serialization.EnumMember(Value = "cai")]
        Cai = 432,
    
        [System.Runtime.Serialization.EnumMember(Value = "cau")]
        Cau = 433,
    
        [System.Runtime.Serialization.EnumMember(Value = "cel")]
        Cel = 434,
    
        [System.Runtime.Serialization.EnumMember(Value = "cmc")]
        Cmc = 435,
    
        [System.Runtime.Serialization.EnumMember(Value = "cpe")]
        Cpe = 436,
    
        [System.Runtime.Serialization.EnumMember(Value = "cpf")]
        Cpf = 437,
    
        [System.Runtime.Serialization.EnumMember(Value = "cpp")]
        Cpp = 438,
    
        [System.Runtime.Serialization.EnumMember(Value = "crp")]
        Crp = 439,
    
        [System.Runtime.Serialization.EnumMember(Value = "cus")]
        Cus = 440,
    
        [System.Runtime.Serialization.EnumMember(Value = "day")]
        Day = 441,
    
        [System.Runtime.Serialization.EnumMember(Value = "dra")]
        Dra = 442,
    
        [System.Runtime.Serialization.EnumMember(Value = "fiu")]
        Fiu = 443,
    
        [System.Runtime.Serialization.EnumMember(Value = "gem")]
        Gem = 444,
    
        [System.Runtime.Serialization.EnumMember(Value = "ijo")]
        Ijo = 445,
    
        [System.Runtime.Serialization.EnumMember(Value = "inc")]
        Inc = 446,
    
        [System.Runtime.Serialization.EnumMember(Value = "ine")]
        Ine = 447,
    
        [System.Runtime.Serialization.EnumMember(Value = "ira")]
        Ira = 448,
    
        [System.Runtime.Serialization.EnumMember(Value = "iro")]
        Iro = 449,
    
        [System.Runtime.Serialization.EnumMember(Value = "kar")]
        Kar = 450,
    
        [System.Runtime.Serialization.EnumMember(Value = "khi")]
        Khi = 451,
    
        [System.Runtime.Serialization.EnumMember(Value = "kro")]
        Kro = 452,
    
        [System.Runtime.Serialization.EnumMember(Value = "map")]
        Map = 453,
    
        [System.Runtime.Serialization.EnumMember(Value = "mkh")]
        Mkh = 454,
    
        [System.Runtime.Serialization.EnumMember(Value = "mno")]
        Mno = 455,
    
        [System.Runtime.Serialization.EnumMember(Value = "mun")]
        Mun = 456,
    
        [System.Runtime.Serialization.EnumMember(Value = "myn")]
        Myn = 457,
    
        [System.Runtime.Serialization.EnumMember(Value = "nah")]
        Nah = 458,
    
        [System.Runtime.Serialization.EnumMember(Value = "nai")]
        Nai = 459,
    
        [System.Runtime.Serialization.EnumMember(Value = "nic")]
        Nic = 460,
    
        [System.Runtime.Serialization.EnumMember(Value = "nub")]
        Nub = 461,
    
        [System.Runtime.Serialization.EnumMember(Value = "oto")]
        Oto = 462,
    
        [System.Runtime.Serialization.EnumMember(Value = "paa")]
        Paa = 463,
    
        [System.Runtime.Serialization.EnumMember(Value = "phi")]
        Phi = 464,
    
        [System.Runtime.Serialization.EnumMember(Value = "pra")]
        Pra = 465,
    
        [System.Runtime.Serialization.EnumMember(Value = "roa")]
        Roa = 466,
    
        [System.Runtime.Serialization.EnumMember(Value = "sai")]
        Sai = 467,
    
        [System.Runtime.Serialization.EnumMember(Value = "sal")]
        Sal = 468,
    
        [System.Runtime.Serialization.EnumMember(Value = "sem")]
        Sem = 469,
    
        [System.Runtime.Serialization.EnumMember(Value = "sgn")]
        Sgn = 470,
    
        [System.Runtime.Serialization.EnumMember(Value = "sio")]
        Sio = 471,
    
        [System.Runtime.Serialization.EnumMember(Value = "sit")]
        Sit = 472,
    
        [System.Runtime.Serialization.EnumMember(Value = "sla")]
        Sla = 473,
    
        [System.Runtime.Serialization.EnumMember(Value = "smi")]
        Smi = 474,
    
        [System.Runtime.Serialization.EnumMember(Value = "son")]
        Son = 475,
    
        [System.Runtime.Serialization.EnumMember(Value = "ssa")]
        Ssa = 476,
    
        [System.Runtime.Serialization.EnumMember(Value = "tai")]
        Tai = 477,
    
        [System.Runtime.Serialization.EnumMember(Value = "tup")]
        Tup = 478,
    
        [System.Runtime.Serialization.EnumMember(Value = "tut")]
        Tut = 479,
    
        [System.Runtime.Serialization.EnumMember(Value = "wak")]
        Wak = 480,
    
        [System.Runtime.Serialization.EnumMember(Value = "wen")]
        Wen = 481,
    
        [System.Runtime.Serialization.EnumMember(Value = "ypk")]
        Ypk = 482,
    
        [System.Runtime.Serialization.EnumMember(Value = "znd")]
        Znd = 483,
    
        [System.Runtime.Serialization.EnumMember(Value = "him")]
        Him = 484,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0))")]
    internal class DateFormatConverter : Newtonsoft.Json.Converters.IsoDateTimeConverter
    {
        public DateFormatConverter()
        {
            DateTimeFormat = "yyyy-MM-dd";
        }
    }

}